# SOURCE
TESTS_DIRECTORY: tests
HEADERS_DIRECTORY: include
SOURCE_DIRECTORY: lib

# COMPILE
OBJECT_DIRECTORY: obj
EXECUTABLES_DIRECTORY: bin

# EXPORT
JSON_DIRECTORY: json
IMAGE_DIRECTORY: img
REPORT_DIRECTORY: report